name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash -el {0}

jobs:
  build:
    strategy:
      max-parallel: 5
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: "test"
        python-version: "3.10"
    - name: Install dependencies
      run: |
        conda install openmeeg flake8 -c conda-forge
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test Python
      run: |
        python compute_leadfields.py
    - name: Test UNIX binaries
      if: ${{ matrix.os }} == "ubuntu-latest"
      run: |
        echo ${PWD}
        ls -laR
        ../compute_leadfields.sh
    - name: Test Windows binaries
      if: ${{ matrix.os }} == "windows-latest"
      shell: cmd
      run: |
        compute_leadfields.bat
